export const vocabulary = [
  { english: "ability", type: "n", chinese: "能力" },
  { english: "abnormal", type: "a", chinese: "異常的" },
  { english: "abort", type: "v", chinese: "中止" },
  { english: "absence", type: "n", chinese: "缺席" },
  { english: "acid", type: "n", chinese: "酸" },
  { english: "active", type: "a", chinese: "主動的" },
  { english: "actual", type: "a", chinese: "真實的" },
  { english: "add", type: "v", chinese: "增加" },
  { english: "adjust", type: "v", chinese: "調整" },
  { english: "Al", type: "n", chinese: "人工智慧" },
  { english: "air shower", type: "n", chinese: "潔淨通道" },
  { english: "alarm", type: "n", chinese: "警報" },
  { english: "alert", type: "n", chinese: "警報" },
  { english: "align", type: "v", chinese: "對焦" },
  { english: "annually", type: "a", chinese: "每年的" },
  { english: "area", type: "n", chinese: "區域" },
  { english: "attach", type: "v", chinese: "附上" },
  { english: "audit", type: "v", chinese: "稽核 查核" },
  { english: "automatic", type: "a", chinese: "自動的" },
  { english: "automotive", type: "adj", chinese: "汽車的" },
  { english: "available", type: "a", chinese: "可使用的" },
  { english: "average", type: "n", chinese: "平均" },
  { english: "backup", type: "n", chinese: "支援" },
  { english: "bank", type: "n/v", chinese: "銀行/暫存" },
  { english: "basic", type: "a", chinese: "基礎的" },
  { english: "beam", type: "n", chinese: "光束" },
  { english: "benchmark", type: "n", chinese: "標竿學習" },
  { english: "bottle", type: "n", chinese: "瓶子" },
  { english: "bottom", type: "n", chinese: "底部" },
  { english: "broken", type: "a", chinese: "破掉的" },
  { english: "cancel", type: "v", chinese: "取消" },
  { english: "card", type: "n", chinese: "卡片" },
  { english: "cart", type: "n", chinese: "手推車" },
  { english: "cassette", type: "n", chinese: "晶片專用盒" },
  { english: "center", type: "n", chinese: "中心" },
  { english: "certify", type: "v", chinese: "證實 驗證" },
  { english: "change", type: "v", chinese: "更換" },
  { english: "chart", type: "n", chinese: "圖表" },
  { english: "check", type: "v", chinese: "檢查" },
  { english: "chemical", type: "n", chinese: "化學 化學品" },
  { english: "chip", type: "n", chinese: "晶片" },
  { english: "choose", type: "v", chinese: "挑選" },
  { english: "clean", type: "v", chinese: "清潔" },
  { english: "clean chamber", type: "n", chinese: "潔淨室" },
  { english: "clear", type: "v", chinese: "清除" },
  { english: "collect", type: "v", chinese: "蒐集" },
  { english: "color", type: "n", chinese: "顏色" },
  { english: "comment", type: "n", chinese: "評論" },
  { english: "company", type: "n", chinese: "公司" },
  { english: "complete", type: "v", chinese: "完成" },
  { english: "computer", type: "n", chinese: "電腦" },
  { english: "concern", type: "v", chinese: "擔憂" },
  { english: "confidential", type: "a", chinese: "機密的" },
  { english: "confirm", type: "v", chinese: "確認" },
  { english: "contamination", type: "n", chinese: "污染" },
  { english: "continue", type: "v", chinese: "繼續" },
  { english: "control", type: "n", chinese: "控制" },
  { english: "copy", type: "n", chinese: "拷貝" },
  { english: "count", type: "v", chinese: "計算" },
  { english: "customer", type: "n", chinese: "客戶" },
  { english: "cycle", type: "n", chinese: "週期" },
  { english: "cycle time", type: "n", chinese: "生產週期" },
  { english: "daily", type: "a", chinese: "每日的" },
  { english: "data", type: "n", chinese: "資料" },
  { english: "date", type: "n", chinese: "日期" },
  { english: "decline", type: "v", chinese: "減少" },
  { english: "defect", type: "n", chinese: "缺陷" },
  { english: "delay", type: "v", chinese: "延遲" },
  { english: "delete", type: "v", chinese: "刪除" },
  { english: "diffusion", type: "n", chinese: "擴散製程" },
  { english: "document", type: "n", chinese: "文件" },
  { english: "dry", type: "a", chinese: "乾的" },
  { english: "emergency", type: "n", chinese: "緊急情況" },
  { english: "emergency stop", type: "n", chinese: "緊急停止" },
  { english: "engineer", type: "n", chinese: "工程師" },
  { english: "enhance", type: "v", chinese: "增強" },
  { english: "enter", type: "v", chinese: "進入" },
  { english: "environment", type: "n", chinese: "環境" },
  { english: "equipment", type: "n", chinese: "設備" },
  { english: "error", type: "n", chinese: "錯誤" },
  { english: "etching", type: "n", chinese: "蝕刻製程" },
  { english: "EUV (extreme ultraviolet)", type: "n", chinese: "極紫外光" },
  { english: "event", type: "n", chinese: "事件" },
  { english: "execute", type: "v", chinese: "執行" },
  { english: "exit", type: "n", chinese: "退出" },
  { english: "fault", type: "n", chinese: "錯誤" },
  { english: "find", type: "v", chinese: "發現" },
  { english: "floor", type: "n", chinese: "地板" },
  { english: "focus", type: "n", chinese: "焦點" },
  { english: "follow", type: "v", chinese: "照做 跟隨" },
  { english: "freeze", type: "v", chinese: "凍結" },
  { english: "full", type: "a", chinese: "滿的" },
  { english: "function", type: "n", chinese: "功能" },
  { english: "gas", type: "n", chinese: "氣體" },
  { english: "glass", type: "n", chinese: "玻璃 鏡片" },
  { english: "gloves", type: "n", chinese: "手套" },
  { english: "grade", type: "n", chinese: "等級" },
  { english: "green", type: "n", chinese: "綠色" },
  { english: "group", type: "n", chinese: "群組" },
  { english: "handle", type: "v", chinese: "處理" },
  { english: "hard-disk", type: "n", chinese: "硬碟" },
  { english: "heavy", type: "a", chinese: "重的" },
  { english: "helmet", type: "n", chinese: "安全帽" },
  { english: "help", type: "v", chinese: "幫助" },
  { english: "hold", type: "v", chinese: "暫停" },
  { english: "hole", type: "n", chinese: "孔 洞" },
  { english: "hot", type: "a", chinese: "熱的" },
  { english: "impact", type: "n", chinese: "影響" },
  { english: "improve", type: "v", chinese: "改善" },
  { english: "inform", type: "v", chinese: "通知" },
  { english: "information", type: "n", chinese: "資訊" },
  { english: "inhibition", type: "n", chinese: "禁止禁用" },
  { english: "input", type: "n", chinese: "輸入" },
  { english: "inspect", type: "v", chinese: "檢查" },
  { english: "inspection", type: "n", chinese: "檢驗" },
  { english: "instruction", type: "n", chinese: "指令" },
  { english: "internet", type: "n", chinese: "網際網路" },
  { english: "interview", type: "n", chinese: "面試" },
  { english: "issue", type: "v/n", chinese: "發行/議題" },
  { english: "job", type: "n", chinese: "工作" },
  { english: "keep", type: "v", chinese: "保持" },
  { english: "keyboard", type: "n", chinese: "鍵盤" },
  { english: "label", type: "n", chinese: "標籤" },
  { english: "laboratory", type: "n", chinese: "實驗室" },
  { english: "leader", type: "n", chinese: "組長" },
  { english: "learn", type: "v", chinese: "學習" },
  { english: "level", type: "n", chinese: "程度" },
  { english: "lift", type: "v", chinese: "抬起 舉起" },
  { english: "light", type: "n", chinese: "光" },
  { english: "line", type: "n", chinese: "直線" },
  { english: "link", type: "n", chinese: "連結" },
  { english: "liquid", type: "n", chinese: "液體" },
  { english: "list", type: "n", chinese: "清單" },
  { english: "lithography", type: "n", chinese: "黃光/微影製程" },
  { english: "load", type: "v", chinese: "上貨 裝載" },
  { english: "loading", type: "n", chinese: "負荷" },
  { english: "lobby", type: "n", chinese: "大廳" },
  { english: "location", type: "n", chinese: "位置" },
  { english: "lock", type: "v", chinese: "鎖住" },
  { english: "log sheet", type: "n", chinese: "工作紀錄" },
  { english: "lose", type: "v", chinese: "遺失" },
  { english: "lot", type: "n", chinese: "批貨" },
  { english: "machine", type: "n", chinese: "機器" },
  { english: "maintain", type: "v", chinese: "維護" },
  { english: "manual", type: "a", chinese: "手動的" },
  { english: "manufacture", type: "v", chinese: "製造" },
  { english: "mark", type: "n", chinese: "記號" },
  { english: "mask", type: "n", chinese: "光罩 口罩" },
  { english: "material", type: "n", chinese: "原料" },
  { english: "measure", type: "v", chinese: "量測" },
  { english: "mechanical", type: "a", chinese: "機械的" },
  { english: "merge", type: "v", chinese: "合併" },
  { english: "message", type: "n", chinese: "訊息" },
  { english: "metal", type: "n", chinese: "金屬" },
  { english: "miss operation", type: "n", chinese: "錯誤動作" },
  { english: "monitor", type: "n", chinese: "監視器 測機" },
  { english: "monthly", type: "a", chinese: "每月的" },
  { english: "more", type: "a", chinese: "更多的" },
  { english: "move", type: "v/n", chinese: "移動/產出" },
  { english: "new", type: "a", chinese: "新的" },
  { english: "normal", type: "a", chinese: "正常的" },
  { english: "note", type: "n", chinese: "註解" },
  { english: "notice", type: "n", chinese: "通知" },
  { english: "number", type: "n", chinese: "號碼" },
  { english: "office", type: "n", chinese: "辦公室" },
  { english: "offline", type: "a", chinese: "離線的" },
  { english: "on time", type: "ph", chinese: "準時" },
  { english: "online", type: "a", chinese: "在線的" },
  { english: "operation", type: "n", chinese: "操作" },
  { english: "output", type: "n", chinese: "輸出" },
  { english: "oven", type: "n", chinese: "烤箱" },
  { english: "over time", type: "ph", chinese: "加班" },
  { english: "page", type: "n", chinese: "頁數" },
  { english: "paper", type: "n", chinese: "紙張" },
  { english: "parameter", type: "n", chinese: "參數" },
  { english: "part", type: "n", chinese: "零件" },
  { english: "particle", type: "n", chinese: "顆粒" },
  { english: "pass", type: "v", chinese: "合格" },
  { english: "passenglish", type: "n", chinese: "密碼" },
  { english: "perfect", type: "a", chinese: "完美的" },
  { english: "personal", type: "a", chinese: "個人的" },
  { english: "phase", type: "n", chinese: "階段" },
  { english: "photo", type: "n", chinese: "相片" },
  { english: "plan", type: "n", chinese: "計劃" },
  { english: "plus", type: "prep", chinese: "加上" },
  { english: "pod", type: "n", chinese: "晶片傳送盒" },
  { english: "point", type: "n", chinese: "點" },
  { english: "position", type: "n", chinese: "位置" },
  { english: "positive", type: "a", chinese: "正向的" },
  { english: "postpone", type: "v", chinese: "延期" },
  { english: "power", type: "n", chinese: "力量" },
  { english: "practice", type: "v", chinese: "練習" },
  { english: "prepare", type: "v", chinese: "準備" },
  { english: "press", type: "v", chinese: "按下" },
  { english: "pressure", type: "n", chinese: "壓力" },
  { english: "preview", type: "n", chinese: "預覽" },
  { english: "price", type: "n", chinese: "價格" },
  { english: "print", type: "n", chinese: "列印" },
  { english: "priority", type: "n", chinese: "優先順序" },
  { english: "process", type: "n", chinese: "過程 流程" },
  { english: "product", type: "n", chinese: "產品" },
  { english: "protect", type: "v", chinese: "保護" },
  { english: "purge", type: "v", chinese: "清除" },
  { english: "push", type: "v", chinese: "推進" },
  { english: "quality", type: "n", chinese: "品質" },
  { english: "quantity", type: "n", chinese: "數量" },
  { english: "rate", type: "n", chinese: "比率" },
  { english: "recertify", type: "v", chinese: "重新認證" },
  { english: "recipe", type: "n", chinese: "食譜 處方程式" },
  { english: "record", type: "n", chinese: "記錄" },
  { english: "recover", type: "v", chinese: "復機" },
  { english: "release", type: "v", chinese: "釋放" },
  { english: "remark", type: "n", chinese: "註記" },
  { english: "remind", type: "v", chinese: "提醒" },
  { english: "remove", type: "v", chinese: "移開" },
  { english: "repair", type: "v", chinese: "修理" },
  { english: "report", type: "n", chinese: "報告" },
  { english: "reset", type: "v", chinese: "重設" },
  { english: "rework", type: "v", chinese: "重做" },
  { english: "route", type: "n", chinese: "路線" },
  { english: "rule", type: "n", chinese: "規則" },
  { english: "run", type: "v", chinese: "運轉 跑" },
  { english: "run-card", type: "n", chinese: "流程卡" },
  {
    english: "SOP(Standard Operating Procedures)",
    type: "n",
    chinese: "標準作業程序",
  },
  { english: "safe", type: "a", chinese: "安全的" },
  { english: "same", type: "a", chinese: "相同的" },
  { english: "save", type: "v", chinese: "儲存" },
  { english: "scrap", type: "n", chinese: "報廢" },
  { english: "scratch", type: "v", chinese: "刮傷" },
  { english: "screen", type: "n", chinese: "螢幕" },
  { english: "select", type: "v", chinese: "選擇" },
  { english: "semiconductor", type: "n", chinese: "半導體" },
  { english: "service", type: "n", chinese: "服務" },
  { english: "sheet", type: "n", chinese: "表單" },
  { english: "shift", type: "n", chinese: "班次" },
  { english: "show", type: "v", chinese: "顯示" },
  { english: "shuttle", type: "n", chinese: "接駁車" },
  { english: "skip", type: "v", chinese: "跳過" },
  { english: "sorter", type: "n", chinese: "排序機 分類機" },
  { english: "source", type: "n", chinese: "來源" },
  { english: "Spec(specification)", type: "n", chinese: "規格" },
  { english: "speed", type: "n", chinese: "速度" },
  { english: "split", type: "n", chinese: "分帳 分批" },
  { english: "stage", type: "n", chinese: "站別 階段" },
  { english: "standard", type: "n", chinese: "標準" },
  { english: "standby", type: "n", chinese: "等待" },
  { english: "start", type: "n", chinese: "啟動" },
  { english: "station", type: "n", chinese: "站" },
  { english: "status", type: "n", chinese: "狀況" },
  { english: "step", type: "n", chinese: "步驟" },
  { english: "stocker", type: "n", chinese: "儲存櫃" },
  { english: "success", type: "n", chinese: "成功" },
  { english: "super", type: "a", chinese: "超級的" },
  { english: "super hot run", type: "n", chinese: "超級急件" },
  { english: "supervisor", type: "n", chinese: "監督者" },
  { english: "support", type: "n", chinese: "支援" },
  { english: "switch", type: "n", chinese: "開關" },
  { english: "system", type: "n", chinese: "系統" },
  { english: "tag", type: "n/v", chinese: "標籤/標註" },
  { english: "take leave", type: "ph", chinese: "請假" },
  { english: "tape", type: "n", chinese: "膠帶" },
  { english: "target", type: "n", chinese: "目標" },
  { english: "technician", type: "n", chinese: "技術員" },
  { english: "telephone", type: "n", chinese: "電話" },
  { english: "temperature", type: "n", chinese: "溫度" },
  { english: "thickness", type: "n", chinese: "厚度" },
  { english: "thin film", type: "n", chinese: "薄膜製程" },
  { english: "time", type: "n", chinese: "時間" },
  { english: "title", type: "n", chinese: "標題" },
  { english: "top", type: "n", chinese: "頂端" },
  { english: "track", type: "v", chinese: "追蹤" },
  { english: "training", type: "n", chinese: "訓練" },
  { english: "trend", type: "n", chinese: "趨勢" },
  { english: "tune", type: "v", chinese: "調整" },
  { english: "turn rate", type: "n", chinese: "周轉率" },
  { english: "unload", type: "v", chinese: "下貨 卸載" },
  { english: "use", type: "v", chinese: "使用" },
  { english: "username", type: "n", chinese: "使用者名稱" },
  { english: "vendor", type: "n", chinese: "廠商" },
  { english: "view", type: "v", chinese: "查看" },
  { english: "wafer", type: "n", chinese: "晶圓" },
  { english: "waiting", type: "n", chinese: "等待" },
  { english: "warning", type: "n", chinese: "警告" },
  { english: "weekly", type: "adv", chinese: "每週地" },
  { english: "wet", type: "a", chinese: "濕的" },
  { english: "window", type: "n", chinese: "視窗" },
  { english: "yield", type: "n", chinese: "良率" },
  { english: "zero", type: "n", chinese: "零" },
];
